### PR TITLE
Improvements of reddit scraper

### LINKED ISSUE #25: Improve Reddit Scraper
* [x] List of subreddits:
- 'worldnews', 'news', 'europe', 'politics', 'upliftingnews', 'truereddit', 'inthenews', 'nottheonion', 'conservative', ... (tbd)

* [x] Fetching:
- Only fetch hot posts
- Properties: title, text, domain of link of post
- Metadata: ID, author (maybe other information about author if available), timestamp
- Fetch top 20 comments per Reddit-Post (here: also get ID)

### PR DESCRIPTION
**Pull request by dnzxy**
Additions and modifications:
- Enriched submission result and comments with additional data
- Added submission and comment author data to result
- Added docker env to config; based on env var scraper can now be started locally or dockerized
- Added pre-commit to requirements; adjusted some pre-comment config parameters
- Reddit scraper now fetches up to 100 hot submissions per subreddit instead of just 100 hot submission of all given subreddits
- Added docstrings to RedditDataCollector class
- Commented in subparser statements for reddit and twitter that were removed before

Necessary `/.vscode/launch.json` to run changes made to `config.json` in this branch with Visual Studio Code:

```json
{
      "name": "Reddit Debug Local",
      "type": "python",
      "request": "launch",
      "program": "<path_to_project>/scraping-scripts/src/data_collection.py",
      "console": "integratedTerminal",
      "justMyCode": false,
      "args": ["--config", "<path_to_project>/scraping-scripts/config.json", "reddit"],
      "env": {
          "SCRAPER_ENV_LOCAL": "true",
      }
  },
  {
      "name": "Reddit Debug Docker",
      "type": "python",
      "request": "launch",
      "program": "<path_to_project>/scraping-scripts/src/data_collection.py",
      "console": "integratedTerminal",
      "justMyCode": false,
      "args": ["--config", "<path_to_project>/scraping-scripts/config.json", "reddit"],
      "env": {
          "SCRAPER_ENV_LOCAL": "false",
      }
 },
```

### CODE REVIEW

**Comment by dnzxy** [comment]
Fixed unit tests by adding a `pytest.ini` to project root and defining `pythonpath` (and `testpaths)`. See [pytest configuration](https://docs.pytest.org/en/7.1.x/reference/customize.html#config-file-formats) and [pytest configuration options](https://docs.pytest.org/en/7.1.x/reference/reference.html#confval-pythonpath) for reference.

**Review by lukasgraef — CHANGES_REQUESTED** [review]
Please remove any tokens or secrets from your config.json before committing

**Comment by dnzxy** [comment]
> Please remove any tokens or secrets from your config.json before committing

@lukasgraef this needs to be handled entirely different, i.e. by setting `config.json`'s contents upon start of `data_collection.py` and reading sensitive data from a `.env`, or similar way. This branch cannot be merged without the `config.json` in its entirety, because our docker image would not be able to run.

**Review by lukasgraef — APPROVED** [review]

**Review by michaeldinzinger — COMMENTED** [review]
If I understand right, in our case we instantiate a new worker for every post (meaning 10 subreddits * 100 posts -> up to 1000 workers); alternative would be to instantiate only 10 workers (one per subreddit); What is the best practice here? Do we add too much overhead here by creating 1000 instead of 10 workers per run?

**Comment by lukasgraef** [comment]
@dim35216: The number of workers is bounded by `max_workers`, which is currently set to 20 workers. You can change this variable in `config.json`.

The number you're refering to is the total amount of futures created. Those get distributed among the 20 workers of our Threadpool, so I think our current implementation should be alright.

**Pull request merged**
